### ISSUE TITLE
Non random jobs generation issue

### ISSUE THREAD

**Issue by RadPowr** [fauxnik/dv-rolling-stock-ownership#73]
After the last update of the mod, jobs stopped being generated randomly. Instead, they are always generated to the same destination. For example, I have empty flatcars on MF. When refreshing jobs, MF-FF jobs with empty Sunomni containers are always generated. At the same time, the input and storage tracks are not occupied in all other places (HB, CM, IMW ...)

**Comment by fauxnik** [comment]
Hi @RadPowr, thanks for your issue report! May I please get the log file from a session in which the problem occurs as well as the step by step process by which I can reproduce the issue?

**Comment by RadPowr** [comment]
[Player.log](https://github.com/fauxnik/dv-rolling-stock-ownership/files/15230798/Player.log)
https://youtu.be/i7v0TOyBUIE
I made a video about this issue and while I was recording, I found 2 more issues. 1. The MF military base can use wagons on non-military tracks to generate work. 2. When loading a train (when approaching it), the wagons
can sometimes collapse, as in the video. But in this case, they already collapsed a long time ago, and I didn't notice it. When this happens for the first time, a bunch of errors fall out in the console and when approaching the station, you can see how the cars fly apart (one car flew so half the map lol).

**Comment by RadPowr** [comment]
![20240507092012_1](https://github.com/fauxnik/dv-rolling-stock-ownership/assets/139383695/47da0ce9-9649-4e93-a253-17d02b8e2b68)

**Comment by RadPowr** [comment]
I checked the job chains and found the ones that are never generated:
GF:
-SU Metal
-SL-FH Empty containers
MF:
-SL-FH Excavators, tractors, empty containers all except Sunomni
-SU Metal from SM
FF:
-SL-FH Empty containers
FM:
-Fur,.. (FM-GF Chain)
CSW:
-SL-FH Empty containers all except Sunomni
SM:
-SL-FH Rails
HB:
-SL-FH Argon, liquid oxygen, Nitrogen
-SL-FH Liquid hydrogen outside the train with black tank cars
-SL-FH Empty containers

**Comment by fauxnik** [comment]
I'm taking a guess that "collapsed" here means damaged? That's already tracked by #21.

It's hard for me to make sense of the video as I can't read the text. I did make some sense of the log file though. Thank you for posting that. It's definitely a bug that wagons are getting jobs assigned to them simultaneously by both Machine Factory and the Military Base. I've created #78 to track this issue.

It looked like you were attempting to get a different destination for FH jobs, were you not? It's intentional that that doesn't happen. Consider taking a SL job like taking a contract to deliver the specified cargo to the specified destination. (The assignment actually happens at cargo load time, but the former works as a simpler approximation.) This "contract" is released when the wagon is unloaded.

If there's anything else related to this issue that I haven't addressed above, please reopen and provide written step-by-step instructions for how to reproduce the issue, in addition to whatever other supporting material you may think necessary to provide (in English please 🙏)

**Comment by RadPowr** [comment]
I didn't mean #21 issue. #21 still exist, but not critical (i use "no fee" mod). Sometimes, when I approach the station, some of the cars may either disappear or fly apart. In that video, just the result of this incident. cars with excavators derailed and damaged (include cargo). But I couldn't capture the moment of collapse itself, unfortunately. This bug happens rarely and unpredictably. But I'm going to try to catch him anyway. If I catch this bug, I will open a new issue.
About FH jobs: If I want to take FH for excavators, then this will not happen. Even SL Job will always be generating with empty 
SunOmni containers. And exactly the same with the chains listed above. Even if SL will generate, I would like to receive money for FH, and not engage in unauthorized transportation.
PS. Train with excavators on screenshoot had loaded before the 3.0.0 update. I meant by this that even if we somehow have a train with another cargo on MF, it will still go to FF (same with SunOmni), even if such a chain should not exist. Excavators are not needed on FF
